const { MongoClient } = require('mongodb');
require('dotenv').config({ path: '../.env' });

const uri = process.env.MONGO_URI;
const dbName = process.env.DB_NAME;
const collectionName = process.env.COLLECTION_NAME;

// const cardRank = {
//   'The Armorer': 2,
//   'Fennec Shand': 1,
//   'Baylan Skoll': 3,
//   'Grand Admiral Thrawn': 1,
//   'Luke Skywalker': 2,
//   'Sabine Wren': 1,
//   'Grand Admiral Sloane': 3,
//   'Moff Gideon': 2,
//   'Ahsoka Tano': 2,
//   'Bo-Katan Kryze': 1,
//   'Cad Bane': 3,
//   Vane: 1,
//   'Ezra Bridger': 2,
//   'The Mandalorian': 1,
//   'Emperor Palpatine': 1,
//   'Shin Hati': 2,
//   'Greef Karga': 2,
//   Grogu: 1,
// };

const cardRank = {
  Enoch: 3,
  'Paz Vizsla': 4,
  'Scorpenek Annihilator Droid': 4,
  Marrok: 4,
  'Hera Syndulla': 3,
  'Rancor Keeper': 4,
  'Grand Admiral Thrawn': 3,
  Wicket: 3,
  'Tatooine Repulsor Train': 3,
  Rukh: 3,
  'Red Leader': 3,
  'Purrgil Ultra': 3,
  'Baylan Skoll': 4,
  'Poe Dameron': 3,
  Outcast: 3,
  'Jabba the Hutt': 4,
  'Corona Four': 4,
  'Barriss Offee': 3,
  'Reanimated Night Trooper': 2,
  'Scion Shuttle': 3,
  'Gar Saxon': 3,
  'Imperial Armored Commando': 4,
  'Shin Hati': 4,
  'Morgan Elsbeth': 4,
  'Reinforcing Light Cruiser': 4,
  Chimaera: 5,
  'Pre Vizsla': 5,
  'Pointless to Resist': 2,
  'Blade of Talzin': 2,
  Huyang: 4,
  'Lothal E-Wing': 3,
  "Duchess's Protector": 3,
  'Leia Organa': 3,
  'Cobb Vanth': 4,
  'Strike Team Vanguard': 4,
  'The Mandalorian': 5,
  "Bo-Katan's Gauntlet": 5,
  'The Armorer': 4,
  'Home One': 4,
  "Luke's Jedi Lightsaber": 4,
  'Get Lost': 4,
  'Domesticated Loth-Cat': 2,
  'Noti Nomad': 2,
  'At Attin Safety Droid': 3,
  'Battered Haulcraft': 3,
  'Doctor Pershing': 2,
  'Palace Chef Droid': 3,
  'Mos Eisley Modifier': 2,
  'Pit Droid Team': 2,
  'Remnant Official': 3,
  'Ryder Azadi': 3,
  'B-Wing Rearguard': 3,
  'Koska Reeves': 5,
  'Covert Believers': 3,
  'Nebulon-C Frigate': 3,
  'Trexler Armored Marauder': 3,
  'Summa-verminoth': 1,
  'Arcana Star Map': 1,
  'Grav Charge': 3,
  'Durasteel Plating': 4,
  'Cybernetic Enhancements': 3,
  'The Conflict Within': 2,
  Perseverance: 2,
  Reforge: 1,
  'Buy Time': 3,
  'Foundling Rescue': 4,
  'Captain Pellaeon': 4,
  'Moff Jerjerrod': 2,
  'Remnant Interceptor': 3,
  'Forest Patroller': 3,
  'Moff Gideon': 4,
  'AT-ST Raider': 4,
  'Gozanti Assault Carrier': 4,
  'Gallius Rax': 3,
  'The Great Mothers': 4,
  Ravager: 2,
  'Long Live the Empire': 1,
  'Dathomiri Magicks': 3,
  'Bo-Katan Kryze': 4,
  'Pathfinder Sergeant': 3,
  'Clan Wren Loyalist': 2,
  'Crix Madine': 2,
  'T-6 Shuttle 1974': 4,
  'Admiral Ackbar': 4,
  'Children of the Watch': 3,
  'Luke Skywalker': 5,
  'Mandalorian Flagship': 3,
  "Sabine's Lightsaber": 3,
  'The Student Guides the Master': 1,
  'Ant Droid': 2,
  'Outland Protector': 2,
  '8D8': 2,
  'Greef Karga': 3,
  'Warrior of Clan Kryze': 3,
  Blurrg: 3,
  'Consortium StarViper': 3,
  Lang: 4,
  'Protectorate Fighter': 2,
  'Stolen Eta Shuttle': 4,
  "Survivors' Langskib": 3,
  'The Twins': 4,
  'Bothan-5': 4,
  'Defenders of the Forest': 3,
  'Fang Fighter Squadron': 3,
  'Dinosaur Turtle': 3,
  'Queen Soruna': 4,
  'Trask Walker': 3,
  "Warrior's Legacy": 3,
  'The Darksaber': 4,
  'Display of Strength': 1,
  'Wipe Them Out': 3,
  'Turning the Tide': 3,
  'Hold Them Off': 4,
  'Stronger Together': 3,
  'TIE Striker': 2,
  'Mortar Trooper': 3,
  'Tempest Lieutenant': 3,
  "Vane's Snub Fighter": 3,
  'Praetorian Elite': 3,
  Justifier: 4,
  'The Cyborg Mech': 4,
  'Ninth Sister': 5,
  Eviscerator: 4,
  'Deadly Vulnerability': 1,
  'Operation Cinder': 2,
  'Inspired Recruit': 3,
  'Green Leader': 3,
  'Honorable Nite Owl': 3,
  Grogu: 3,
  'R5-D4': 3,
  'Danger Squadron Wingmen': 3,
  'Han Solo': 3,
  'Alphabet Squadron U-Wing': 4,
  'Kachirho Militia': 4,
  'Zeb Orrelios': 4,
  'Rash Action': 2,
  'Reckless Sacrifice': 4,
  'Alamite Hunter': 2,
  'Clan Vizsla Soldier': 3,
  'Ewok Warrior': 3,
  'Flarestar Attack Shuttle': 3,
  'Migs Mayfeld': 4,
  'Axe Woves': 3,
  'Desert Sharpshooter': 3,
  'Pegasus Tri-Wing': 3,
  'Razor Crest': 4,
  'Shydopp Pirate Skiff': 3,
  'StarFortress Heavy Bomber': 4,
  'Wookiee Chieftain': 3,
  'Imposing Scout Walker': 4,
  'Onyx Cinder': 4,
  'Knobby White Ice Spider': 3,
  "Boba Fett's Rancor": 3,
  'Bokken Saber': 2,
  'Mark My Words': 1,
  'Unfettered Ambition': 3,
  'Whistling Birds': 4,
  'Follow Me': 1,
  Intimidation: 2,
  'Treacherous Minefield': 1,
  Reckoning: 3,
  'Galvanized Leap': 1,
  "Emperor's Messenger": 1,
  'Peridea Bandit': 3,
  "Shin Hati's Fiend Fighter": 3,
  'Fennec Shand': 3,
  "Emperor's Champion": 3,
  'Snub Fighter Squadron': 3,
  Helgait: 5,
  "Gorian Shard's Corsair": 5,
  Executor: 3,
  'Nowhere to Hide': 1,
  'There Is No Conflict': 3,
  Rehabilitation: 4,
  'Open Circle Ace': 2,
  'Carson Teva': 4,
  "Mando's N-1 Starfighter": 2,
  'Blade Three': 3,
  'Inspiring Veteran': 3,
  'Kelleran Beq': 4,
  'Heroic Purrgil': 3,
  'Sabine Wren': 5,
  'Ezra Bridger': 4,
  'DDC Defender': 2,
  'Fateful Goodbye': 2,
  'Peli Motto': 2,
  'Womp Rat': 2,
  'Amnesty Officer': 3,
  'Flanking TIE Interceptor': 3,
  'Mandalorian Scout': 3,
  "Mayor's Majordomo": 3,
  'Ferry Droid': 3,
  'Jod Na Nawood': 5,
  'Remnant Lookouts': 3,
  'Helix Starfighter': 3,
  'Unsanctioned Patrol': 3,
  Halo: 3,
  'Elzar Mann': 4,
  'Tatooine Sand Beast': 3,
  "Qi'ra": 4,
  'Heightened Awareness': 1,
  Preparation: 1,
  Camtono: 1,
  'Improvised Identity': 1,
  'Diplomatic Pageantry': 2,
  'Full of Surprises': 2,
  'Keep Them Talking': 2,
  Masterstroke: 2,
  'Sense Through the Force': 1,
  'Far Far Away': 3,
  'Mouse Droid': 1,
  'Attendant Navigator': 3,
  'Imperial Loyalist': 3,
  'Mandalorian Super Commandos': 3,
  "Marrok's Fiend Fighter": 3,
  'Death Trooper Squad': 2,
  'Darth Vader': 4,
  'Remnant Trooper Corps': 3,
  'Eye of Sion': 3,
  'Exploit Advantage': 2,
  'One Must Destroy to Create': 1,
  Neel: 2,
  'Covert Veteran': 3,
  'Imperial Defector': 3,
  'Zealous Soldier': 3,
  'N5 Sentry Droid': 3,
  'Yellow Aces Bomber': 3,
  'Gallofree Transport': 3,
  'Anakin Skywalker': 4,
  'Rebel Infiltrators': 3,
  'Choose Your Path': 1,
  'Grassroots Resistance': 3,
  'LEP Ratcatcher': 2,
  'Mos Espa Watermonger': 2,
  'Noti Mobile Pod': 3,
  'Faith in the Empire': 1,
  "The Way of the Mand'alor": 1,
  'A New Order': 1,
};

async function updateRanks() {
  const client = new MongoClient(uri);

  try {
    await client.connect();
    const db = client.db(dbName);
    const collection = db.collection(collectionName);

    let totalUpdated = 0;

    for (const [name, rank] of Object.entries(cardRank)) {
      const result = await collection.updateMany(
        { Name: name, Set: 'ASH', Type: { $ne: 'Leader' } },
        { $set: { Rank: rank } },
      );
      console.log(
        `Updated ${result.modifiedCount} document(s) for Name: "${name}"`,
      );
      totalUpdated += result.modifiedCount;
    }

    console.log(`Done! Total documents updated: ${totalUpdated}`);
  } catch (err) {
    console.error('Error updating ranks:', err);
  } finally {
    await client.close();
  }
}

updateRanks();
