const { MongoClient } = require('mongodb');
require('dotenv').config({ path: '../.env' });

const uri = process.env.MONGO_URI;
const dbName = process.env.DB_NAME;
const collectionName = process.env.COLLECTION_NAME;

const cardRank = {
  'Asajj Ventress': 1,
  'Maz Kanata': 1,
  'Doctor Hemlock': 2,
  'Grand Moff Tarkin': 1,
  'Jar Jar Binks': 2,
  Omega: 1,
  'Darth Vader': 2,
  'General Grievous': 2,
  Chewbacca: 2,
  Tarfful: 3,
  'Darth Sidious': 1,
  'Poggle the Lesser': 1,
  'Cham Syndulla': 1,
  Wicket: 1,
  Bossk: 1,
  Maul: 1,
  Osha: 1,
  'The Warrior': 3,
};

// const cardRank = {
//   Hunter: 5,
//   Kelnacca: 4,
//   'Bacta Tank': 2,
//   'Bestial Bond': 2,
//   'Mother Talzin': 3,
//   "Talzin's Shuttle": 3,
//   'Keeper of Skara Nal': 2,
//   Dooku: 4,
//   'Darth Vader': 3,
//   'Ima-Gun Di': 3,
//   Logray: 3,
//   Krrsantan: 4,
//   Eravana: 4,
//   'Vernestra Rwoh': 3,
//   'Greater Sarlacc': 4,
//   'Low Altitude Combat': 3,
//   'Third Sister': 3,
//   "A'Koba": 3,
//   "Fett's Firespray": 3,
//   'Seismic Detonation': 2,
//   Mae: 3,
//   Yoda: 3,
//   'Boss Lyonie': 3,
//   'Mysterious Disappearance': 3,
//   'Clone X Assassin': 3,
//   'Vice Admiral Rampart': 2,
//   'Director Krennic': 3,
//   'Nuvo Vindi': 3,
//   'Rho Medical Shuttle': 2,
//   Scorch: 4,
//   'Clone of the Zillo Beast': 2,
//   'Carrion Spike': 2,
//   'The Great Progenitor': 3,
//   'Imperial Commandos': 4,
//   'Imperial Venator': 3,
//   'Dark Sanctum': 1,
//   Ravage: 3,
//   'Grand Army Marine': 4,
//   'Peppi Bow': 3,
//   'Yord Fandar': 4,
//   'Wookiee Protector': 3,
//   Yanna: 3,
//   'Boss Nass': 4,
//   'Qui-Gon Jinn': 4,
//   'Radiant VII': 3,
//   'Fambaa Shield Team': 2,
//   'Alliance Shield Generator': 2,
//   'Nala Se': 1,
//   Batcher: 4,
//   'Gunga City Guard': 3,
//   'Remote Scout': 2,
//   'N-1 Patroller': 3,
//   'Venomous Wyyyshokk': 3,
//   Numa: 3,
//   'Territorial Mudhorn': 3,
//   'Opee Sea Killer': 3,
//   'Pelta Relief Frigate': 3,
//   'Starlit Purrgil': 3,
//   'Coastal Catamarans': 3,
//   'Sando Aqua Monster': 3,
//   'Carbonite Chamber': 2,
//   Devotion: 2,
//   'Dire Prowess': 3,
//   Resonate: 1,
//   'Always a Bigger Fish': 1,
//   Torrent: 3,
//   'Trust Yourself': 2,
//   "Dragon's Might": 3,
//   'Disposable B1': 2,
//   Garnac: 3,
//   'Nute Gunray': 3,
//   'Secessionist Convert': 3,
//   'Stormtrooper Patrol': 3,
//   'The First Legion': 4,
//   'Tireless Magnaguard': 4,
//   'Emperor Palpatine': 5,
//   'Invasion Lander': 3,
//   'Military Academy': 1,
//   'Sinister War Memorial': 1,
//   Breach: 4,
//   'Leia Organa': 3,
//   'Ewok Brigade': 4,
//   Chewbacca: 2,
//   'Ryyk Blademaster': 4,
//   'Saw Gerrera': 4,
//   'Auzituck Avenger': 4,
//   'Hijacked AT-ST': 2,
//   Boga: 3,
//   'King Grakchawwaa': 2,
//   'Luminara Unduli': 5,
//   'The Marauder': 3,
//   'Verdant Fortress': 1,
//   "Chewbacca's Bowcaster": 3,
//   'Mace Windu': 1,
//   'Child of Dathomir': 2,
//   'Emerie Karr': 3,
//   'Soaring Can-Cell': 3,
//   'Tibidee Mate': 2,
//   'Wroshyr Rebel': 2,
//   'Zam Wesell': 4,
//   'Arena Reek': 4,
//   'Lifetree Caravan': 2,
//   'V-19 Skirmisher': 2,
//   'Commander Gree': 4,
//   'Flock of Mynocks': 3,
//   'Assault Frigate': 4,
//   Rex: 3,
//   'Wookiee Rangers': 4,
//   'Banking Clan Warship': 3,
//   'Howler Pack': 3,
//   'Origin Tree Shyyyo': 4,
//   'Outer Rim Garrison': 3,
//   'Beast Lair': 1,
//   'Local Support': 2,
//   'Log Trap': 2,
//   Migrate: 3,
//   Overgrowth: 3,
//   'Babwa Venomor': 2,
//   "Poacher's Starfighter": 3,
//   "Dooku's Solar Sailer": 3,
//   'Filthy Dianoga': 4,
//   'Arena Acklay': 3,
//   'Corpo Thugs': 3,
//   'Battle-Scarred Destroyer': 3,
//   'General Grievous': 5,
//   'Noxious Refinery': 1,
//   'Raze to Ruin': 1,
//   Teebo: 3,
//   'Champions of Endor': 4,
//   'Chief Chirpa': 2,
//   'Commandeered Tour Shuttle': 3,
//   Gungi: 3,
//   'Dune Sea Nomads': 4,
//   'Ezra Bridger': 4,
//   Crosshair: 4,
//   'Han Solo': 2,
//   'Trap Field': 3,
//   'Heavy Ion Cannon': 2,
//   'Rebel Operation': 1,
//   Maul: 1,
//   'Fennec Shand': 2,
//   'Village Troublemaker': 2,
//   'Adamant Ewoks': 3,
//   'Desperate Nantex': 3,
//   'Feisty Blurrg': 2,
//   Stormchaser: 3,
//   'Tusken Bantha Rider': 3,
//   'Arena Nexu': 3,
//   'Nightsister Prodigy': 3,
//   Aggrocrab: 3,
//   'Ty Yorrick': 2,
//   'Mining Guild Trespasser': 3,
//   'Dathomiri Rancor': 3,
//   'Giant Gorax': 4,
//   'Neebray Manta': 2,
//   Enraged: 3,
//   "Hunter's Instinct": 2,
//   'Volley Fire': 1,
//   Nightfall: 3,
//   'Run Amok': 3,
//   'Catch the Scent': 3,
//   Qimir: 3,
//   'Cid Scaleback': 3,
//   'Treacherous Pyke': 3,
//   'Geonosian Picador': 3,
//   'Rish Loo': 2,
//   'Sandtrooper Squad': 3,
//   'Inferno Squad': 4,
//   'Victor Squadron': 4,
//   Nightbrother: 4,
//   'Intelligence Agency': 1,
//   'The Tarkin Doctrine': 1,
//   Maim: 2,
//   'Luke Skywalker': 3,
//   'Corona Squadron X-Wing': 3,
//   Sol: 4,
//   Tech: 4,
//   'The Chieftain': 3,
//   'Tribubble Bongo Sub': 3,
//   'Phee Genoa': 3,
//   'L3-37': 3,
//   'Insurgent Camp': 2,
//   "Don't Touch Anything": 2,
//   'New Tactics': 3,
//   Jaxxon: 1,
//   'Clever Trapper': 3,
//   Teeka: 2,
//   'Sandcrawler Sales Team': 3,
//   'Therm Scissorpunch': 1,
//   'Tusken Raider': 3,
//   'Boba Fett': 3,
//   'Gungan Battle Wagon': 3,
//   'Horizon Chaser': 3,
//   'Lakeside Shaaks': 2,
//   'Lurking Wampa': 3,
//   'Raiding Party': 2,
//   'Dragonboat Freighter': 3,
//   'Mon Cal Cruiser': 4,
//   'Awakened Exogorth': 3,
//   'Ritual Dragon': 4,
//   'Gaderffii Stick': 3,
//   'Booma Ball': 3,
//   'Easy Prey': 2,
//   'Exploit Confidence': 4,
//   Pounce: 2,
//   Sandstorm: 3,
//   Howl: 4,
//   'Occupation Officer': 3,
//   'Sun Fac': 3,
//   'Separatist Harbinger': 3,
//   'Trandoshan Collaborator': 3,
//   'Pyke Sarisa': 3,
//   'Surveillance Cruiser': 3,
//   'Defoliator Tank': 3,
//   'Frenzied Tri-Fighters': 3,
//   'Imperial Cavalry': 3,
//   'Blockade Ship': 3,
//   'Villainous Ambition': 3,
//   'Forced Pacification': 2,
//   'Captain Tarpals': 3,
//   'C-3PO': 3,
//   'Jedi Interceptor': 2,
//   'Ewok Archers': 3,
//   'Ryloth Revolutionary Rider': 3,
//   'Pack Guardian': 3,
//   'Queen Amidala': 2,
//   'Ben Kenobi': 4,
//   'Mylaya Rider': 3,
//   Wrecker: 3,
//   'Heroic Bravery': 3,
//   "Twi'lek Kalikori": 1,
//   'Familiar Strategem': 2,
//   Renew: 1,
//   'Offworld Jawa': 2,
//   'Friendly Eopie': 2,
//   'Wild Space Wanderer': 2,
//   'Landing Pad': 1,
//   Growth: 2,
// };

async function updateRanks() {
  const client = new MongoClient(uri);

  try {
    await client.connect();
    const db = client.db(dbName);
    const collection = db.collection(collectionName);

    let totalUpdated = 0;

    for (const [name, rank] of Object.entries(cardRank)) {
      const result = await collection.updateMany(
        { Name: name, Set: 'HMW', Type: 'Leader' },
        // { Name: name, Set: 'HMW', Type: { $ne: 'Leader' } },
        { $set: { Rank: rank } },
      );
      console.log(
        `Updated ${result.modifiedCount} document(s) for Name: "${name}"`,
      );
      totalUpdated += result.modifiedCount;
    }

    console.log(`Done! Total documents updated: ${totalUpdated}`);
  } catch (err) {
    console.error('Error updating ranks:', err);
  } finally {
    await client.close();
  }
}

updateRanks();
