const { MongoClient } = require('mongodb');
require('dotenv').config()

const uri = process.env.MONGO_URI;
const dbName = process.env.DB_NAME;
const collectionName = process.env.COLLECTION_NAME;

const cardRank = {
    "The Chancellor's Shuttle": 3,
    "Trayus Acolyte": 4,
    "Zam Wesell": 3,
    "Death Trooper": 3,
    "Nute Gunray": 3,
    "Kylo Ren's Command Shuttle": 3,
    "Sly Moore": 3,
    "Cad Bane": 4,
    "Darth Sion": 4,
    "Dogmatic Shock Squad": 3,
    "Cantwell Arrestor Cruiser": 2,
    "Condemn": 4,
    "Creditor's Claim": 4,
    "Emergency Powers": 5,
    "Populist Advisor": 3,
    "Cassian Andor": 4,
    "Chandrilan Sponsor": 3,
    "Populist Champion": 3,
    "Senator Chuchi": 3,
    "Galen Erso": 3,
    "Coronet": 3,
    "Captain Rex": 5,
    "Jade Squadron Patrol": 3,
    "Vigil": 2,
    "Bo-Katan Kryze": 3,
    "Diplomatic Immunity": 3,
    "One in a Million": 1,
    "Exiled From the Force": 1,
    "Dhani Pilgrim": 2,
    "Escape Pod": 1,
    "Lobot": 2,
    "Lost Jedi": 2,
    "Senate Warden": 2,
    "Defense Fleet X-Wing": 2,
    "Willrow Hood": 3,
    "Bardottan Ornithopter": 3,
    "Rotunda Senate Guards": 3,
    "Congress of Malastare": 3,
    "Nala Se": 3,
    "Alderaanian Envoys": 3,
    "Umbaran Mobile Cannon": 3,
    "Lando Calrissian": 4,
    "Nimble Prowess": 3,
    "Armor of Fortune": 2,
    "Disciples' Devotion": 3,
    "Scour the Archives": 1,
    "The Eye of Aldhani": 2,
    "Relief Request": 2,
    "Knowledge and Defense": 3,
    "Charged with Murder": 3,
    "Retaliation": 3,
    "Hyperspace Disaster": 1,
    "Corrupt Politician": 2,
    "Imperial Dark Trooper": 4,
    "Major Partagaz": 2,
    "Chancellor Palpatine": 5,
    "ISB Shuttle": 3,
    "Mas Amedda": 4,
    "Vice Admiral Rampart": 3,
    "Cruel Commandos": 3,
    "Dedra Meero": 4,
    "First Light": 3,
    "PreMor Personnel Carrier": 3,
    "Director Krennic": 3,
    "Corporate Warmongering": 2,
    "I Am the Senate": 3,
    "C-3P0": 2,
    "Mina Bonteri": 4,
    "Theed Security": 3,
    "Ahsoka Tano": 3,
    "Beloved Orator": 3,
    "Captain Typho": 4,
    "Naboo Royal Starship": 4,
    "Dressellian Commandos": 4,
    "Queen Amidala": 5,
    "Renowned Dignitaries": 3,
    "Mon Mothma": 5,
    "Figure of Unity": 4,
    "Renewed Friendship": 2,
    "Dismantle the Conspiracy": 3,
    "Chancellor Valorum": 1,
    "Senator's Aide": 2,
    "Diplomatic Envoy": 2,
    "GNK Power Droid": 2,
    "Jar Jar Binks": 4,
    "Orn Free Taa": 1,
    "Daro Commando": 3,
    "Kino Loy": 2,
    "Taylander Shuttle": 3,
    "Nubian Star Skiff": 3,
    "Consular's Cruiser": 3,
    "Raxian Assembly": 3,
    "Crucible": 4,
    "Naboo Security Force": 3,
    "Shadow Crawler": 3,
    "Vuutun Palaa": 1,
    "Unveiled Might": 3,
    "Budget Scheming": 2,
    "Reconnaissance": 2,
    "Trade Route Taxation": 1,
    "Charged with Corruption": 3,
    "Convene the Senate": 2,
    "With Thunderous Applause": 2,
    "Ferrix Uprising": 3,
    "Let's Talk": 3,
    "Imperial Occupier": 3,
    "Syril Karn": 3,
    "Hunting Assassin Droid": 3,
    "Muckraker Crab Droid": 3,
    "Arihnda Pryce": 3,
    "Dryden Vos": 2,
    "Enforcer Squadron": 3,
    "Miraj Scintel": 4,
    "Hondo Ohnaka": 3,
    "The Galleon": 3,
    "Fulminatrix": 4,
    "The Elite Squad": 4,
    "Tempest Assault": 2,
    "Confidence in Victory": 1,
    "Rebellious Functionary": 2,
    "Chopper": 3,
    "Karis Nemik": 4,
    "Kaydel Connix": 2,
    "Valiant Commando": 2,
    "Kazuda Xiono": 4,
    "Strike Force X-Wing": 3,
    "Luthen's Haulcraft": 4,
    "Inner Rim Coalition": 3,
    "Alexsandr Kallus": 5,
    "Nemik's Manifesto": 1,
    "One Way Out": 2,
    "Oppression Breeds Rebellion": 2,
    "Chairman Papanoida": 1,
    "Reckless Rebel": 2,
    "Contraband Starhopper": 3,
    "Crosshair": 3,
    "Outer Rim Constable": 3,
    "Warrior of Clan Ordo": 4,
    "Academy Disciplinarian": 3,
    "Republic Aurek Starfighter": 2,
    "Coruscant Undercity Police": 3,
    "Ziton Moj": 4,
    "AAT Incinerator": 3,
    "Corellian Hounds": 2,
    "Punishing One": 4,
    "Cinta Kaz": 4,
    "Republic War Walker": 3,
    "Saw Gerrera's U-wing": 3,
    "Ambition's Reward": 2,
    "Sudden Ferocity": 4,
    "It's Not Over Yet": 1,
    "Pursue the Lead": 1,
    "Aggressive Negotiations": 3,
    "Let's Call It War": 4,
    "Unauthorized Investigation": 2,
    "Charged with Treason": 3,
    "Topple the Summit": 4,
    "ISB Agent": 2,
    "Screeching TIE Fighter": 2,
    "Garindan": 2,
    "General Grievous": 1,
    "Darth Traya": 3,
    "Lurking Snub Fighter": 3,
    "Soulless One": 3,
    "Trade Federation Delegates": 3,
    "Grand Moff Tarkin": 3,
    "Grand Admiral Thrawn": 5,
    "Fully Armed and Operational": 4,
    "Arrest": 4,
    "No One Ever Knew": 3,
    "Furtive Handmaiden": 2,
    "Bail Organa": 4,
    "Bravo Squadron Fighter": 3,
    "Junior Senator": 3,
    "Anakin Skywalker": 3,
    "Rebel Propagandist": 2,
    "Tala Durith": 2,
    "Blue Ace": 4,
    "Obi-Wan Kenobi": 4,
    "Emissaries from Ryloth": 3,
    "Lightmaker": 5,
    "Hunter": 4,
    "The Mandalorian": 5,
    "Stolen Starpath Unit": 2,
    "Faith in Your Friends": 1,
    "Libertine": 1,
    "A-Wing": 2,
    "Skyhopper Canyon Runner": 2,
    "Emissary's Sheathipede": 3,
    "Regulations Bureaucrat": 2,
    "Zenuas Shadow Fighter": 2,
    "Cikatro Vizago": 4,
    "Ebon Hawk": 4,
    "Hired Slicer": 3,
    "Unruly Astromech": 3,
    "Loan Shark": 4,
    "Duchess's Investigators": 3,
    "Vel Sartha": 4,
    "Synara San": 4,
    "Sneaking Suspicion": 2,
    "Special Modifications": 1,
    "Accelerate Our Plans": 3,
    "Catch Unawares": 2,
    "Charged with Espionage": 2,
    "Implicate": 2,
    "Kreia's Whispers": 3,
    "Beguile": 4,
    "Bog Down in Procedure": 2,
    "The Wrong Ride": 2,
    "Undercover Operation": 2,
    "Supreme Council Aide": 2,
    "Sith Assassin": 3,
    "Viper Probe Droid": 3,
    "Hutt Cartel Starfighter": 2,
    "Political Bully": 3,
    "Elia Kane": 4,
    "FN Trooper Corps": 3,
    "Darth Nihilus": 5,
    "When Has Become Now": 1,
    "Contempt for Culture": 3,
    "Evil Is Everywhere": 1,
    "B2EMO": 1,
    "High Command Councilor": 3,
    "Rebel Pathfinder": 3,
    "Crait Veteran": 2,
    "Maarva Andor": 3,
    "Covert Operative": 3,
    "Heroic ARC-170": 3,
    "Remote Escort Tank": 3,
    "Moral Authority": 4,
    "Restore Freedom": 1,
    "Grassroots Resistance": 2,
    "ASP Laborer": 2,
    "Inspector's Shuttle": 2,
    "Inspiring Senator": 3,
    "Ando Commission": 3,
    "Assassin Probe": 3,
    "Clandestine Connections": 2
};

async function updateRanks() {
    const client = new MongoClient(uri);

    try {
        await client.connect();
        const db = client.db(dbName);
        const collection = db.collection(collectionName);

        let totalUpdated = 0;

        for (const [name, rank] of Object.entries(cardRank)) {
            const result = await collection.updateMany(
                { Name: name, Set: 'SEC', Type: { $ne: "Leader" } },
                { $set: { Rank: rank } }
            );
            console.log(`Updated ${result.modifiedCount} document(s) for Name: "${name}"`);
            totalUpdated += result.modifiedCount;
        }

        console.log(`Done! Total documents updated: ${totalUpdated}`);
    } catch (err) {
        console.error('Error updating ranks:', err);
    } finally {
        await client.close();
    }
}

updateRanks();
