const knownTraits = [
    'armor',
    'bounty',
    'bounty hunter',
    'capital ship',
    'clone',
    'condition',
    'creature',
    'disaster',
    'droid',
    'ewok',
    'fighter',
    'first order',
    'force',
    'fringe',
    'gambit',
    'gungan',
    'hutt',
    'imperial',
    'innate',
    'inquisitor',
    'item',
    'jawa',
    'jedi',
    'kaminoan',
    'law',
    'learned',
    'lightsaber',
    'mandalorian',
    'modification',
    'naboo',
    'new republic',
    'night',
    'nihil',
    'official',
    'pilot',
    'plan',
    'rebel',
    'republic',
    'resistance',
    'separatist',
    'sith',
    'spectre',
    'speeder',
    'supply',
    'tactic',
    'tank',
    'transport',
    'trick',
    'trooper',
    'tusken',
    'twi\'lek',
    'undead',
    'underworld',
    'vehicle',
    'walker',
    'weapon',
    'wookiee',
];

module.exports = knownTraits;